file2md:
  output_root: "./test_outputs"
  prefer:
    txt: "txt"
    docx: "mineru" # mineru
    excel: "excel"
    html: "beautifulsoup"
    pdf: "mineru"
    pptx: "mineru"
    image: "mineru"

providers:
  mineru:
    base_url: "http://localhost:8962/"
    timeout_sec: 60
    retry: 2
    default_extra:
      backend: "pipeline"
      parse_method: "auto"

converters:
  txt:
    txt:
      extra:
        wrap_in_codeblock: false
        smart_format: true
        normalize_line_endings: true
        strip_trailing_spaces: true
  docx:
    mammoth:
      extra:
        extract_images: true
        keep_output: true
        default_convert_image_format: "png"
        image_alt_text: ""
    mineru:
      extra: 
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
  pdf:
    mineru:
      extra:
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
  pptx:
    mineru:
      extra:
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
  html:
    beautifulsoup:
      extra:
        extract_images: true
        keep_output: true
        convert_image_format: "png"
        download_remote_images: false
  image:
    mineru:
      extra:
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
  excel:
    excel:
      extra: {}
