file2md:
  output_root: "./output"
  prefer:
    txt: "txt"
    docx: "mammoth" # mineru
    excel: "excel"
    html: "beautifulsoup"
    pdf: "mineru"
    pptx: "mineru"
    image: "mineru"

llm:
  default_model: "Gemma-3-12B-IT"
  default_config_path: "./configs/models.yaml"
  default_params:
    temperature: 0.2
    max_tokens: 2000

providers:
  mineru:
    base_url: "http://10.204.245.170:8962/"
    timeout_sec: 600
    retry: 2
    default_extra:
      backend: "pipeline"
      parse_method: "auto"

converters:
  txt:
    txt:
      extra:
        wrap_in_codeblock: false
        smart_format: true
        normalize_line_endings: true
        strip_trailing_spaces: true
  docx:
    mammoth:
      extra:
        extract_images: true
        keep_output: true
        default_convert_image_format: "png"
        image_alt_text: ""
        parse_image: true
    mineru:
      extra: 
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
        parse_image: true
  pdf:
    mineru:
      extra:
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
        parse_image: true
  pptx:
    mineru:
      extra:
        return_images: true
        keep_unzipped: true
        draw_layout_bbox: true
        draw_span_bbox: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
        parse_image: true
  html:
    beautifulsoup:
      extra:
        extract_images: true
        keep_output: true
        convert_image_format: "png"
        download_remote_images: false
  image:
    mineru:
      extra:
        return_images: true
        keep_unzipped: true
        return_images: true
        return_middle_json: true
        response_format_zip: true
  excel:
    excel:
      extra: {}
