params:
    default:
        temperature: 0.2
        max_tokens: 1000
        top_p: 1
        frequency_penalty: 1.4
        presence_penalty: 0

LLM_engines:
    gpt-4o:
        model: "gpt-4o"
        azure_api_base: 
        azure_api_key: 
        azure_api_version: 
        translate_to_cht: True
    Qwen3-0.6B:
        model: "Qwen3-0.6B"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8801/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Mistral-Small-3.2-24B-Instruct-2506:
        model: "/models/max/llm/Mistral-Small-3.2-24B-Instruct-2506"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Mistral-Small-3.2-24B-Instruct-2506-INT4:
        model: "Mistral-Small-3.2-24B-Instruct-2506-INT4"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Mistral-Small-3.2-24B-Instruct-2506-FP8:
        model: "/models/max/llm/Mistral-Small-3.2-24B-Instruct-2506-FP8"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT:
        model: "gemma-3-12b-it"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-Checkpoint-100-DPO:
        model: "gemma-3-12b-it-checkpoint-100-dpo"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-Checkpoint-200-DPO:
        model: "gemma-3-12b-it-checkpoint-200-dpo"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-Checkpoint-300-DPO:
        model: "gemma-3-12b-it-checkpoint-300-dpo"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-Checkpoint-400-DPO:
        model: "gemma-3-12b-it-checkpoint-400-dpo"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-400:
        model: "gemma-3-12b-it-grpo-400"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-500:
        model: "gemma-3-12b-it-grpo-500"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-600:
        model: "gemma-3-12b-it-grpo-600"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-700:
        model: "gemma-3-12b-it-grpo-700"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-800:
        model: "gemma-3-12b-it-grpo-800"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-1000:
        model: "gemma-3-12b-it-grpo-1000"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-1100:
        model: "gemma-3-12b-it-grpo-1100"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-1300:
        model: "gemma-3-12b-it-grpo-1300"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-1500:
        model: "gemma-3-12b-it-grpo-1500"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-1700:
        model: "gemma-3-12b-it-grpo-1700"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-1900:
        model: "gemma-3-12b-it-grpo-1900"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-GRPO-2100:
        model: "gemma-3-12b-it-grpo-2100"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-DPO-300:
        model: "gemma-3-12b-it-dpo-300"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional
    Gemma-3-12B-IT-merge_2_stages:
        model: "gemma-3-12b-it-merge_2_stages"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8963/v1"
        translate_to_cht: True # optional, whether to translate the input to Chinese Traditional


embedding_models:
    m3e-base:
        model: "m3e-base"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8887/v1"
    bge-m3:
        model: "bge-m3"
        local_api_key: "Empty"
        local_base_url: "your_local_base_url"

reranking_models:
    bge-reranker-large:
        model: "bge-reranker-large"
        local_api_key: "Empty"
        local_base_url: "your_local_base_url"
    bge-reranker-base:
        model: "bge-reranker-base"
        local_api_key: "Empty"
        local_base_url: "http://localhost:8887/v1"